### ISSUE TITLE
Problem with Keyconversion

### ISSUE THREAD

**Issue by buschhardt** [maik/xml-simple#18]
Hallo, I try to convert a XML-String

```xml
<d:propfind xmlns:d="DAV:" xmlns:cs="http://calendarserver.org/ns/">
  <d:prop>
     <d:displayname />
     <cs:getctag />
  </d:prop>
</d:propfind>
```
but XmlSimple.xml_in(xml,{'KeepRoot'=>true}) convert this to:
```
{"propfind"=>[
  {"xmlns:d"=>"DAV:", "xmlns:cs"=>"http://calendarserver.org/ns/",
  "prop"=>[{
     "displayname"=>[{}],
     "getctag"=>[{}]
    }]
  }
]}
```
The __d:propfind__, __d:prop__, __d:displayname__ and __cs:getctag__ incorrect converted to String.
Is a option for that or is it a bug?

Danke

**Comment by maik** [comment]
Hi!

Currently, xml-simple does not support namespaces.

Best,
Maik

On Thu, May 7, 2015 at 2:32 PM, Buschhardt <notifications@github.com> wrote:

> Hallo, I try to convert a XML-String
>
> <d:propfind xmlns:d="DAV:" xmlns:cs="http://calendarserver.org/ns/">
>   <d:prop>
>      <d:displayname />
>      <cs:getctag />
>   </d:prop>
> </d:propfind>
>
> but XmlSimple.xml_in(xml,{'KeepRoot'=>true}) convert this to:
>
> {"propfind"=>[
>   {"xmlns:d"=>"DAV:", "xmlns:cs"=>"http://calendarserver.org/ns/",
>   "prop"=>[{
>      "displayname"=>[{}],
>      "getctag"=>[{}]
>     }]
>   }
> ]}
>
> The *d:propfind*, *d:prop*, *d:displayname* and *cs:getctag* incorrect
> converted to String.
> Is a option for that or is it a bug?
>
> Danke
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maik/xml-simple/issues/18>.
>



-- 
Start simple or fail!

I am a software developer, hardware enthusiast, and a writer:

* Arduino: A Quick-Start Guide (http://pragprog.com/book/msard2/)
* Raspberry Pi: A Quick-Start Guide (http://pragprog.com/book/msraspi2/)
* Enterprise Recipes with Ruby and Rails (http://pragprog.com/book/msenr/)
* Enterprise Integration with Ruby (http://pragprog.com/book/fr_eir/)

Follow me on Twitter: @maik_schmidt

**Comment by buschhardt** [comment]
Hallo Maik,
hmm but if I use a wrong namespace, there is a support, see:
```xml
<card:addressbook-multiget xmlns:d="DAV:" xmlns:card="urn:ietf:params:xml:ns:carddav">
    <d:prop>
        <d:getetag />
        <c:addressbook-data />
    </d:prop>
    <d:href>/addressbooks/johndoe/contacts/abc-def-fez-123454657.vcf</d:href>
    <d:href>/addressbooks/johndoe/contacts/acme-12345.vcf</d:href>
</card:addressbook-multiget>
```
The __c:addressbook-data__ is wrong and XmlSimple remark this.

**Comment by maik** [comment]
Hi!

Yes, the underlying parser is aware of namespaces, I think, and it rejects
invalid XML. Still, xml-simple does not interpret namespaces properly.

Best,
Maik


On Fri, May 8, 2015 at 11:27 AM, Buschhardt <notifications@github.com>
wrote:

> Hallo Maik,
> hmm but if I use a wrong namespace, there is a support, see:
>
> <card:addressbook-multiget xmlns:d="DAV:" xmlns:card="urn:ietf:params:xml:ns:carddav">
>     <d:prop>
>         <d:getetag />
>         <c:addressbook-data />
>     </d:prop>
>     <d:href>/addressbooks/johndoe/contacts/abc-def-fez-123454657.vcf</d:href>
>     <d:href>/addressbooks/johndoe/contacts/acme-12345.vcf</d:href>
> </card:addressbook-multiget>
>
> The *c:addressbook-data* is wrong and XmlSimple remark this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maik/xml-simple/issues/18#issuecomment-100172136>.
>



-- 
Start simple or fail!

I am a software developer, hardware enthusiast, and a writer:

* Arduino: A Quick-Start Guide (http://pragprog.com/book/msard2/)
* Raspberry Pi: A Quick-Start Guide (http://pragprog.com/book/msraspi2/)
* Enterprise Recipes with Ruby and Rails (http://pragprog.com/book/msenr/)
* Enterprise Integration with Ruby (http://pragprog.com/book/fr_eir/)

Follow me on Twitter: @maik_schmidt

**Comment by buschhardt** [comment]
Hallo Maik,
Thank You
