### ISSUE TITLE
Funky Output wth Camel Case Variables

### ISSUE THREAD

**Issue by otaviof** [maik/xml-simple#19]
Hello,

This piece of code is providing some funky output when dealing with Camel Case variables, tested with `xml-simple v1.1.5`. Where "content" is not correctly parsed still printed out as, Ruby Hash, although if you change "content" variable to something like "contentCamelCasedTest" the problem does not appear anymore. Also, if removed other variables that start with "content" plus Camel Case values, the problem is also avoided.

Please consider:

```Ruby
require 'xmlsimple'

test = {
  'subClientProperties' => {
    'subClientEntity' => {
      'appName' => 'app_name',
      'backupsetName' => 'backup_set_name',
      'clientName' => 'cv_clientname',
      'instanceName' => 'DefaultInstanceName',
      'subclientName' => 'subclient_name',
    },
    'commonProperties' => {
      'enableBackup' => 'true'
    },
    'content' => {
      'path' => [
        '/var/tmp',
        '/var/lib/test'
      ]
    },
  }
}

xs = XmlSimple.new(
  { 'ForceArray' => [ "path" ],
    'KeepRoot' => false,
    'NoEscape' => true,
    'RootName' => "App_CreateSubClientRequest",
    'AttrPrefix' => true,
  }
)

puts xs.xml_out test
```

Output:

```
irb(main):033:0* puts xs.xml_out test
<App_CreateSubClientRequest>
  <subClientProperties>{"path"=>["/var/tmp", "/var/lib/test"]}<subClientEntity>
      <appName>app_name</appName>
      <backupsetName>backup_set_name</backupsetName>
      <clientName>cv_clientname</clientName>
      <instanceName>DefaultInstanceName</instanceName>
      <subclientName>subclient_name</subclientName>
    </subClientEntity>
    <commonProperties>
      <enableBackup>true</enableBackup>
    </commonProperties>
  </subClientProperties>
</App_CreateSubClientRequest>
=> nil
```

**Comment by maik** [comment]
Hi!

I am a bit in a hurry at the moment, but I guess the problem is the key
named "content". Please, have a look at the section named "ContentKey" in
the gem's manual (http://xml-simple.rubyforge.org/).

Best,
Maik


On Wed, May 20, 2015 at 10:32 AM, Otávio Fernandes <notifications@github.com
> wrote:

> Hello,
>
> This piece of coding is providing some funky output when dealing with
> Camel Case variables, tested with xml-simple v1.1.5. Where "content" is
> not correctly parsed still printed out as, Ruby Hash, although if you
> change "content" variable to something like "contentCamelCasedTest" the
> problem does not appear anymore. Also, if removed other variables that
> start with "content" plus Camel Case values, the problem is also avoided.
>
> Please consider:
>
> require 'xmlsimple'
>
> test = {
>   'subClientProperties' => {
>     'subClientEntity' => {
>       'appName' => 'app_name',
>       'backupsetName' => 'backup_set_name',
>       'clientName' => 'cv_clientname',
>       'instanceName' => 'DefaultInstanceName',
>       'subclientName' => 'subclient_name',
>     },
>     'commonProperties' => {
>       'enableBackup' => 'true'
>     },
>     'content' => {
>       'path' => [
>         '/var/tmp',
>         '/var/lib/test'
>       ]
>     },
>   }
> }
>
> xs = XmlSimple.new(
>   { 'ForceArray' => [ "path" ],
>     'KeepRoot' => false,
>     'NoEscape' => true,
>     'RootName' => "App_CreateSubClientRequest",
>     'AttrPrefix' => true,
>   }
> )
>
> puts xs.xml_out test
>
> Output:
>
> irb(main):033:0* puts xs.xml_out test
> <App_CreateSubClientRequest>
>   <subClientProperties>{"path"=>["/var/tmp", "/var/lib/test"]}<subClientEntity>
>       <appName>app_name</appName>
>       <backupsetName>backup_set_name</backupsetName>
>       <clientName>cv_clientname</clientName>
>       <instanceName>DefaultInstanceName</instanceName>
>       <subclientName>subclient_name</subclientName>
>     </subClientEntity>
>     <commonProperties>
>       <enableBackup>true</enableBackup>
>     </commonProperties>
>   </subClientProperties>
> </App_CreateSubClientRequest>
> => nil
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maik/xml-simple/issues/19>.
>



-- 
Start simple or fail!

I am a software developer, hardware enthusiast, and a writer:

* Arduino: A Quick-Start Guide (http://pragprog.com/book/msard2/)
* Raspberry Pi: A Quick-Start Guide (http://pragprog.com/book/msraspi2/)
* Enterprise Recipes with Ruby and Rails (http://pragprog.com/book/msenr/)
* Enterprise Integration with Ruby (http://pragprog.com/book/fr_eir/)

Follow me on Twitter: @maik_schmidt

**Comment by otaviof** [comment]
Indeed @maik, using "ContentKey" corrected the output, thanks for the quick response!

```Diff
@@ -27,6 +27,7 @@ xs = XmlSimple.new(
     'NoEscape' => true,
     'RootName' => "App_CreateSubClientRequest",
     'AttrPrefix' => true,
+    'ContentKey' => '+content'
   }
 )
```
