### ISSUE TITLE
Feature request - (does this make sense to you?)

### ISSUE THREAD

**Issue by mistergibson** [maik/xml-simple#24]
Dear Maik,

I was wondering if you could add a feature to xml_out and xml_in where: when it produces xml from a Hash it sets a 'ruby_class' attribute to the class of the data element for the key or array element key for each element, and casting the text to that ruby_class when producing the Ruby Hash/Array?

Does such a feature make sense to you? If not, what are your thoughts?

Thanks in advance, (great gem btw)

G. Gibson
mistergibson

**Comment by maik** [comment]
Hi!

Thank you very much for your suggestion! I thought about doing something
similar in the past to turn xml-simple into a full-blown object-to-xml
mapping tool. I decided not to do it, because it would add a lot more
complexity with only a small benefit.

Best,
Maik

**Comment by mistergibson** [comment]
I heard that nokogiri does this, and it runs under jruby like yours. I'll see if that holds any promise.

Thanks for the reply
