### ISSUE TITLE
nil instead of {}

### ISSUE THREAD

**Issue by mickael-palma-argus** [maik/xml-simple#25]
Hi,

When I do this:
```ruby
XmlSimple.xml_in('<fiche><generation/></fiche>', 'ForceArray' => false)
```
I get this in return:
```ruby
{"generation"=>{}}
```

I want to get:
```ruby
{"generation"=>nil}
```

How can I do it?

Thanks for your help.

**Comment by maik** [comment]
You have to use the SuppressEmpty option:

`XmlSimple.xml_in('<fiche><generation/></fiche>', 'ForceArray' => false, 'SuppressEmpty' => nil)`

**Comment by mickael-palma-argus** [comment]
Wow, that was fast.

Thank you.
