### ISSUE TITLE
Docs currently failing to build on rubydoc.info

### ISSUE THREAD

**Issue by markwilkinson** [maik/xml-simple#28]
https://www.rubydoc.info/gems/xml-simple/1.1.5

spins and spins

**Comment by maik** [comment]
Hi Mark!

Thank you very much for reporting this issue! Do you have any more details?
When I run rdoc locally against the code, it runs just fine.

Best,
Maik

**Comment by maik** [comment]
I have checked it on rubydoc.info and it seems to work fine.
